### PR TITLE
Rework willingly-taken curse lists

### LINKED ISSUE #9: Acceptable curses for companions
One thing that someone brought up in the reddit thread is that companions may want to accept different curses if they have been swapped into a new body. For example, if a female PC swaps bodies with Khemia, then he'd happily take on a Sex Switcheroo curse that he'd normally be averse to. 

Currently we're using a constant for this, which means it won't change over the course of the game. And I think that makes sense for now. I suspect this might require a lot of work to solve for a relatively small benefit to players, so effort is better used elsewhere, but if either of you think there's an elegant solution to this problem then we can add it in. If not, then this should probably be lower priority than most of the other updates.

### PR DESCRIPTION
**Pull request by Annonymus-v02**
Closes #9 by reworking the willingly-taken curses to be computed rather than based on a static list.

Companions now have a list of curses they will always take (e.g. Age Reduction A for Lily) and will also take curses that bring them closer to the way they used to be:
 - They'll take gender reversal curses if their current gender does not align with original gender (and the curse will take them closer).
 - Men who find themselves with breasts and no penis will take Shrunken Assets to get rid of the breasts.
 - Anybody who's currently female will take hair removal.
 - If they have opposite genitals they'll take Sex Switcheroo.
 - If they can't get Sex Switcheroo they'll settle for both sets with Futa Fun instead.
 - Men with a womb will take Absolute Birth Control, because they do not want to get pregnant.

Some open questions:
 - What happens to the sexuality of sex-switched companions? Will they still only have sex with people of the (now) same gender (assuming they were hetero before)? Or only with people of the sex they used to be? Or both? If the latter, sex-switched companions may be willing to take Equal Opportunity.
 - Does Khemia still want Pheromones if they are sex-switched?
 - Is Cherry not willing to take the literalization curse? I realise it's in the as-of-yet unimplemented layer, but it might make sense to add it to her already so we don't forget later.
 - Does maru want to become feminine or remain androgynous? It seemed to me like the latter is the case, but his (former) willingness to take gender reversal curses despite already starting at a gender of 3 seems to imply the opposite. For now I've implemented his desires assuming he wants to be androgynous.
 - Will maru take shrunken assets to become more androgynous?
 - Is Maru ok with having a vagina or will he want to switch back to a penis if sex-switched? If his penis grows too large and starts to bulge, will he *prefer* a vagina? If so at which size (currently I've set it to >6)?
 - Men with a womb will take Absolute Birth Control even if they still have a penis. Does that make sense? IMO the dysphoria of getting pregnant would be stronger than a desire to eventually maybe have kids, but those with a strong parental drive might argue that they can rely on regular birth control instead.
 - Any other suggestions for curses that companions might want to take under some circumstances, or additional circumstances under which they might want to take curses already listed above?

This isn't really about this PR, but I noticed the futa curse description and picture implies that recipients end up with a penis and breasts, but the implementation also gives them a vagina.

One more thing I want to do is give each companion an ideal size for their assets and make them choose curses until they get there. I haven't implemented that yet because it would get complicated with having to figure out which asset a curse would increase, depending on the curses they already have.
I've already been meaning to rework the computed attributes so they are returned by a function on the person objects instead of being stored and periodically recomputed. That would make them easier to understand and use and make implementing this step easier too, so I'll hold off on size goals until then, unless you tell me you'd rather keep the current system.

Another, incidental addition is that the stat adjustment page now allows taking and removing curses and relics.
I found it useful for testing, but also see it being used for narrative effects that can manipulate relics and curses, e.g. a relic that allows duplication like the kin shifter, or which interacts with curses like Managed Misfortune.

### CODE REVIEW

**Comment by FloricSpacer** [comment]
This is great stuff! I agree this is a better way to handle willing Curses than what is used now.

The ability to adjust Curses and Relics from the adjustment screen is also a welcome improvement!

I have a few comments about it, which I'll share here. But in general, I prefer to have most of the development discussion on the Abyss Diver's Discord server. Since you're making more complex PRs which can benefit from discussion, it might be best if you could join the Discord server to make that discussion easier. Though if you're opposed to using Discord for some reason, you're free to just post things here, I definitely appreciate the contributions regardless!

https://discord.com/invite/gXnq5rmjxG

But here's my comments on this PR and the other questions you have:

1. I think you have a good logic for companions taking gender-related Curses in general. But I think the way you have it currently coded won't work with the body swapping function. Since a body swap changes the osex and ogender of the person who is swapped (which is intended). But that means that if, for example, Khemia swapped with a female MC, then Khemia's osex would be female and his ogender would be very feminine, so he would willingly take Curses that make him more feminine. Maybe to account for this, you can check the player's osex rather than the companion's osex for a companion which has switched with the player? Or we could have an oosex which is a constant for each companion and would never change?
2. I don't think everyone who's female would take hair removal. Men in a female body might prefer to have more body hair to remind them of their old body, rather than embracing femininity.
3. I think that Cloud and Khemia would take absolute birth control if they're female, but Maru would not, since he values family and the chance to have children eventually higher than them.
4. None of the sex/gender changing Curses have any mental effect, so companions who change sex are attracted to the same gender they were initially. For example, Khemia prefers women, and if he became female then he would still prefer women.
5. Khemia would still be fine with pheromones if he swapped sex.
6. I think Cherry would be willing to take the literalization Curse only if it would make her a cat, but not if it would make her a plant/lizard/tentacle monster/etc.
7. I think Maru's ideal gender level is slightly more feminine than he is now (since it would make him cuter), but not completely. So he starts at a 3, but his ideal would be a 4, so he would take 1 gender reversal Curse.
8. Maru doesn't dislike his penis or anything like that, so he wouldn't want to reduce its size or anything similar. He would prefer to have a penis than a vagina. And while he wouldn't willingly grow the size of his penis, he wouldn't want to get rid of it just for being large either. 
9. Yes, I agree with you about men wanting absolute birth control, again with the exception of Maru who doesn't want to give up a chance at a family.
10. I don't have any other conditional acceptance suggestions now, but I'll think about it!

Other comments:
1. Yeah, I think Futa Fun is due a slight rework where the player can choose whether they end up with only penis + breasts, or penis + vagina + breasts, but I haven't gotten around to it.
2. Computing asset sizes and ideal asset sizes sounds like a good idea, I'd definitely be open to that change! SpikyMoth is also refactoring a significant amount of code too though, so it might be worth checking with them to make sure you aren't both working on the same thing.

Thanks again for all this help! I really, really appreciate it!

**Comment by Annonymus-v02** [comment]
I could investigate swapping some more and write a solution specific to that, but I think it makes more sense to keep track of the companions' *desired* gender and base it on that. This allows more flexibility and could in theory be used for other effects which affect gender identity (e.g., a curse that turns cis characters trans without changing their body). `gender` sounds like a good name for that, but... we already have a variable with that name so I guess I'd call it `mindSex`? Does that sound alright?

**Comment by Annonymus-v02** [comment]
Actually another one we'd need is `comfortableHeight`, so that swapped companions take height-changing curses until they're back at their original height.

**Comment by Annonymus-v02** [comment]
It looks like height-changing effects on companions are affected by the player's choice of direction (decrease/increase). Is that intentional? It would make sense for each individual to choose separately, although then we'd have to represent that somehow (an extra event in the log inserted together with the first curse?)

**Comment by Annonymus-v02** [comment]
I'll hold off on the desired asset size and desired height until after the companion rework which will make this easier. Everything else should work now.

**Review by FloricSpacer — APPROVED** [review]

**Comment by FloricSpacer** [comment]
Yeah, all of that sounds good to me. mindSex is a reasonable name, since we're already using gender for the relative masculinity/femininity of the characters.

The desired height changes also seem reasonable to me, though yeah, we'd need to add something to track the direction if that's different from the player's choice.

**Pull request merged**
